### Librerias

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

### Importar csv

In [2]:
csv_libros='lectulandia_books_1.csv'
df=pd.read_csv(csv_libros)
df

url  \
0    https://ww3.lectulandia.com/book/el-medico-de-...   
1    https://ww3.lectulandia.com/book/un-espia-en-l...   
2    https://ww3.lectulandia.com/book/una-mujer-sin...   
3    https://ww3.lectulandia.com/book/los-dias-de-p...   
4      https://ww3.lectulandia.com/book/rey-del-mundo/   
..                                                 ...   
471  https://ww3.lectulandia.com/book/ni-de-eva-ni-...   
472  https://ww3.lectulandia.com/book/el-mundo-de-a...   
473  https://ww3.lectulandia.com/book/mi-vida-en-la...   
474  https://ww3.lectulandia.com/book/einstein-su-v...   
475  https://ww3.lectulandia.com/book/ines-del-alma...   

                              titulo                    autor  \
0             El médico de Auschwitz             Szymon Nowak   
1           Un espía en la trinchera  Enrique Bocanegra Vidal   
2          Una mujer sin importancia            Sonia Purnell   
3                  Los días de París                   Banine   
4                      Rey del mundo            David Remnick   
..                               ...                      ...   
471             Ni de Eva ni de Adán           Amélie Nothomb   
472                 El mundo de ayer             Stefan Zweig   
473        Mi vida en la Fórmula Uno               Jo Ramírez   
474  Einstein: Su vida y su universo          Walter Isaacson   
475              Inés del alma mía           Isabel Allende   

                                             autor_url  \
0      https://ww3.lectulandia.com/autor/szymon-nowak/   
1    https://ww3.lectulandia.com/autor/enrique-boca...   
2     https://ww3.lectulandia.com/autor/sonia-purnell/   
3            https://ww3.lectulandia.com/autor/banine/   
4     https://ww3.lectulandia.com/autor/david-remnick/   
..                                                 ...   
471  https://ww3.lectulandia.com/autor/amelie-nothomb/   
472    https://ww3.lectulandia.com/autor/stefan-zweig/   
473      https://ww3.lectulandia.com/autor/jo-ramirez/   
474  https://ww3.lectulandia.com/autor/walter-isaac...   
475  https://ww3.lectulandia.com/autor/isabel-allende/   

                                              sinapsis  \
0    Enero de 1945. Hay 4.800 prisioneros en Auschw...   
1    Una apasionante investigación sobre las activi...   
2    En septiembre de 1941, una joven estadounidens...   
3    ElOrient Expressse dirige a toda velocidad hac...   
4    La historia de uno de los más grandes atletas ...   
..                                                 ...   
471                                                NaN   
472                                                NaN   
473                                                NaN   
474                                                NaN   
475                                                NaN   

                                            imagen_url  \
0    https://assets.lectulandia.com/b/ab/Szymon%20N...   
1    https://assets.lectulandia.com/b/ab/Enrique%20...   
2    https://assets.lectulandia.com/b/ab/Sonia%20Pu...   
3    https://assets.lectulandia.com/b/ab/Banine/Los...   
4    https://assets.lectulandia.com/b/ab/David%20Re...   
..                                                 ...   
471  https://assets.lectulandia.com/b/Amelie%20Noth...   
472  https://assets.lectulandia.com/b/Stefan%20Zwei...   
473  https://assets.lectulandia.com/b/Jo%20Ramirez/...   
474  https://assets.lectulandia.com/b/Walter%20Isaa...   
475  https://assets.lectulandia.com/b/Isabel%20Alle...   

                                       generos  
0           Biografía - Divulgación - Historia  
1    Biografía - Crónica - Historia - Política  
2    Biografía - Crónica - Historia - Política  
3    Biografía - Crónica - Historia - Memorias  
4                          Biografía - Crónica  
..                                         ...  
471                      Biografía - Romántico  
472                      Biografía - Histórico  
473                                  Biog

### Ejercicio 1

In [5]:
# Corpus simple para practicar
sinopsis_ejemplo = [
    "Una historia de amor en tiempos de guerra",
    "Aventuras mágicas en un mundo fantástico",
    "Un detective resuelve misterios en la ciudad",
    "Romance juvenil en una escuela",
    "Ciencia ficción sobre viajes en el tiempo"
]

def ejercicio_vectorizacion_basica(sinopsis):
    """
    Implementar y comparar:
    1. Count Vectorizer básico
    2. TF-IDF básico
    3. Mostrar las matrices resultantes
    4. Calcular similitud entre la primera y segunda sinopsis
    """
    print("=== EJERCICIO DE VECTORIZACIÓN BÁSICA ===\n")

    # 1. Count Vectorizer básico
    print("1. COUNT VECTORIZER")
    print("-" * 40)

    count_vectorizer = CountVectorizer()
    count_matrix = count_vectorizer.fit_transform(sinopsis)

    print("Vocabulario:", count_vectorizer.get_feature_names_out())
    print("\nMatriz Count Vectorizer:")
    print(count_matrix.toarray())

    # Mostrar como DataFrame para mejor visualización
    count_df = pd.DataFrame(count_matrix.toarray(),
                           columns=count_vectorizer.get_feature_names_out(),
                           index=[f"Doc {i+1}" for i in range(len(sinopsis))])
    print("\nMatriz como DataFrame:")
    print(count_df)

    # 2. TF-IDF básico
    print("\n\n2. TF-IDF VECTORIZER")
    print("-" * 40)

    tfidf_vectorizer = TfidfVectorizer()
    tfidf_matrix = tfidf_vectorizer.fit_transform(sinopsis)

    print("Vocabulario:", tfidf_vectorizer.get_feature_names_out())
    print("\nMatriz TF-IDF:")
    print(tfidf_matrix.toarray())

    # Mostrar como DataFrame para mejor visualización
    tfidf_df = pd.DataFrame(tfidf_matrix.toarray(),
                           columns=tfidf_vectorizer.get_feature_names_out(),
                           index=[f"Doc {i+1}" for i in range(len(sinopsis))])
    print("\nMatriz TF-IDF como DataFrame:")
    print(tfidf_df.round(3))

    # 3. Calcular similitud entre la primera y segunda sinopsis
    print("\n\n3. CÁLCULO DE SIMILITUD")
    print("-" * 40)

    # Similitud usando Count Vectorizer
    count_sim = cosine_similarity(count_matrix[0:1], count_matrix[1:2])[0][0]
    print(f"Similitud coseno (Count Vectorizer) entre Doc1 y Doc2: {count_sim:.4f}")

    # Similitud usando TF-IDF
    tfidf_sim = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])[0][0]
    print(f"Similitud coseno (TF-IDF) entre Doc1 y Doc2: {tfidf_sim:.4f}")

    # 4. Comparación de todas las similitudes
    print("\n\n4. MATRIZ DE SIMILITUDES COMPLETA")
    print("-" * 40)

    # Matriz de similitudes Count Vectorizer
    count_similarities = cosine_similarity(count_matrix)
    print("Similitudes Count Vectorizer:")
    count_sim_df = pd.DataFrame(count_similarities,
                               index=[f"Doc {i+1}" for i in range(len(sinopsis))],
                               columns=[f"Doc {i+1}" for i in range(len(sinopsis))])
    print(count_sim_df.round(3))

    # Matriz de similitudes TF-IDF
    tfidf_similarities = cosine_similarity(tfidf_matrix)
    print("\nSimilitudes TF-IDF:")
    tfidf_sim_df = pd.DataFrame(tfidf_similarities,
                               index=[f"Doc {i+1}" for i in range(len(sinopsis))],
                               columns=[f"Doc {i+1}" for i in range(len(sinopsis))])
    print(tfidf_sim_df.round(3))

    return count_matrix, tfidf_matrix, count_similarities, tfidf_similarities

# Ejecutar el ejercicio
count_matrix, tfidf_matrix, count_sim, tfidf_sim = ejercicio_vectorizacion_basica(sinopsis_ejemplo)

=== EJERCICIO DE VECTORIZACIÓN BÁSICA ===

1. COUNT VECTORIZER
----------------------------------------
Vocabulario: ['amor' 'aventuras' 'ciencia' 'ciudad' 'de' 'detective' 'el' 'en'
 'escuela' 'fantástico' 'ficción' 'guerra' 'historia' 'juvenil' 'la'
 'misterios' 'mundo' 'mágicas' 'resuelve' 'romance' 'sobre' 'tiempo'
 'tiempos' 'un' 'una' 'viajes']

Matriz Count Vectorizer:
[[1 0 0 0 2 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 1 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0]
 [0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1]]

Matriz como DataFrame:
       amor  aventuras  ciencia  ciudad  de  detective  el  en  escuela  \
Doc 1     1          0        0       0   2          0   0   1        0   
Doc 2     0          1        0       0   0          0   0   1        0   
Doc 3     0          0        0       1   0          1   0   1        0   
Doc 4     0          